/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include "STM32F401xx.h"
#include "GPIOdriver.h"

// Busy-wait delay function
void delay(uint32_t count) {
    for(uint32_t i = 0; i < count; i++);
}
uint8_t PA5state;
int main(void) {
    // GPIO Handle configuration for task 1 (User LED - PA5)
    GPIO_Handle_t LED_Handle;
    LED_Handle.pGPIOx = GPIOA;
    LED_Handle.GPIO_PinConfig.GPIO_PinNumber = GPIO_PIN_NO_5;
    LED_Handle.GPIO_PinConfig.GPIO_PinMode = GPIO_MODE_OUT;
    LED_Handle.GPIO_PinConfig.GPIO_PinOPType = GPIO_OP_TYPE_PP;
    LED_Handle.GPIO_PinConfig.GPIO_PinSpeed = GPIO_SPEED_FAST;
    LED_Handle.GPIO_PinConfig.GPIO_PinPuPdContol = GPIO_NO_PUPD;


    // Peripheral Clock Initialization
    GPIO_PeriClockControl(GPIOA, ENABLE);

    // GPIO Initialization
    GPIO_Init(&LED_Handle);



    while(1) {

    	 GPIOA->ODR &= ~(1<< 5);// 101111
    	 delay(1000);
    	  GPIOA->ODR |= (1<<5);//.....010000                      // 010000
    	  delay(1000);
            }

}

