/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F401RE.h"
#include "stm32f401re_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(){
	for(uint32_t i=0;i<300000;i++);
}
int main(void)
{
	GPIO_Handle_t GPIOled;// declare structure variable for handle structure
	GPIO_Handle_t GPIOread;// for reading button press

	GPIOled.pGPIOx=GPIOA;
	GPIOled.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIOled.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
	GPIOled.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	GPIOled.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PUSHPULL;
	GPIOled.GPIO_PinConfig.GPIO_PinPUPD=GPIO_NO_PUPD;        // set required configurations for PA5

	GPIO_Init(&GPIOled);// initialize PA5

	GPIOread.pGPIOx=GPIOC;
	GPIOread.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_13;  // button is active low
	GPIOread.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IN ;     // configure pin PC13, on-board button
	GPIOread.GPIO_PinConfig.GPIO_PinPUPD = GPIO_PIN_PULLUP; // internal pull-up


	GPIO_Init(&GPIOread);// initialize PC13

	GPIO_Handle_t led1, led2;// external LED blink

	led1.pGPIOx= GPIOA;
	led2.pGPIOx= GPIOA;
	led1.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_0;
	led2.GPIO_PinConfig.GPIO_PinNumber= GPIO_PIN_NO_1;
    led1.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
    led2.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
    led1.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
    led2.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
    led1.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PUSHPULL;
    led2.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PUSHPULL;// set configurations for led1 and led2

    GPIO_Init(&led1);
    GPIO_Init(&led2);// initialize PA0 and PA1

    GPIO_Write_OutputPin(GPIOA, GPIO_PIN_NO_0, 1);
    GPIO_Write_OutputPin(GPIOA, GPIO_PIN_NO_1, 0);// set PA0 as HIGH and PA1 as LOW at first

    uint8_t current_state=1, prev_state=1;
    uint32_t count=0, time=0;// to set up a software counter

	while(1)
	{
		current_state=GPIO_Read_InputPin(GPIOC, GPIO_PIN_NO_13);

		if(prev_state==1 && current_state==0)// button press creates falling edge
		{
			GPIO_Toggle_OutputPin(GPIOA ,GPIO_PIN_NO_5);// toggle LED
		}
		prev_state= current_state;// update previous state

		if(count-time > 200000)// non-blocking delay
		{
			GPIO_Toggle_OutputPin(GPIOA, GPIO_PIN_NO_0 );
			GPIO_Toggle_OutputPin(GPIOA, GPIO_PIN_NO_1 );
			time=count;// update time
		}
         count++;
	}

}








