/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F401RE.h"
#include "stm32f401re_gpio_driver.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay(){
	for(uint32_t i=0;i<300000;i++);
}
int main(void)
{
	GPIO_Handle_t GPIOled;// declare structure variable for handle structure
	GPIO_Handle_t GPIOread;// for reading button press

	GPIOled.pGPIOx=GPIOA;
	GPIOled.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_5;
	GPIOled.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_OUT;
	GPIOled.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;
	GPIOled.GPIO_PinConfig.GPIO_PinOPType=GPIO_OP_TYPE_PUSHPULL;
	GPIOled.GPIO_PinConfig.GPIO_PinPUPD=GPIO_NO_PUPD;        // set required configurations for PA5

	GPIO_Init(&GPIOled);// initialize PA5

	GPIOread.pGPIOx=GPIOC;
	GPIOread.GPIO_PinConfig.GPIO_PinNumber=GPIO_PIN_NO_13;
	GPIOread.GPIO_PinConfig.GPIO_PinMode=GPIO_MODE_IN ;     // configure pin PC13, on-board button
	GPIOread.GPIO_PinConfig.GPIO_PinPUPD = GPIO_PIN_PULLUP; // internal pull-up

	//GPIOread.GPIO_PinConfig.GPIO_PinSpeed=GPIO_SPEED_FAST;

	GPIO_Init(&GPIOread);// initialize PC13

	while(1)
	{
		if(GPIO_Read_InputPin(GPIOC, 13)==0)// button press
		{
			 GPIO_Write_OutputPin(GPIOA, 5, 1);// set PA5 as HIGH
		}
		else
		{
			 GPIO_Write_OutputPin(GPIOA, 5, 0);// set PA5 as LOW
		}

	}

}








