/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdio.h>

#include "SSD1306.h"
#include "SSD1306_Graphics.h"


//Application is using I2C1 instance for communication

static void force_delay()
{
	for(int i=0; i<700000;i++);
}
static void GPIO_Configurations_SCL_SDA()
{

	// Set GPIO Configurations
	// - PB8 and PB9 are used as SCl and SDA of I2C1 instance
	// - Use alternate function AF4
	// - SCL and SDA are open drain with pull up
	GPIOB_CLK_EN();
	GPIOB->MODER  &=~((0x3<< 8*2)|(0x3<< 9*2));
	GPIOB->MODER  |= (0x2<< 8*2)|(0x2<< 9*2);
	GPIOB->AFR[1] &=~((0xF<<0*4)|(0xF<< 1*4));
	GPIOB->AFR[1] |= ((0x4<<0*4)|(0x4<< 1*4));
	GPIOB->OTYPER |= (1<< 8)|(1<< 9);
	GPIOB->PUPDR &=~((0x3<< 8*2)|(0x3<< 9*2));
	GPIOB->PUPDR |= ((0x1<< 8*2)|(0x1<< 9*2));
	GPIOB->OSPEEDR &=~((0x3<< 8*2)|(0x3<< 9*2));
	GPIOB->OSPEEDR |=((0x3<< 8*2)|(0x3<< 9*2));

}
static void I2C1_Configurations()
{
	I2C_Handle_t i2c1;

	i2c1.pI2Cx = I2C1;
	i2c1.I2C_Config.I2C_SCL_Speed = I2C_SCL_SPEED_FM;
	i2c1.I2C_Config.I2C_SCL_DutyCycle = I2C_FM_DUTY_2;

	I2C_Init(&i2c1);

	I2C_PeripheralControl(I2C1, ENABLE);
}


int main(void)
{
	GPIO_Configurations_SCL_SDA();

	I2C1_Configurations();

	SSD1306_t oled;
	oled.I2C_Address = OLED_ADDRESS;
	oled.I2C_interface = I2C1;
	oled.contrast = 0xFF;
	oled.orientation = OLED_ORIENTATION_ROTATE180;

	SSD1306_Init(&oled);

	GFX_Clear(&oled);

	//SSD1306_DisplayInvert(&oled, false);

	//GFX_DrawPixel(&oled, 40, 10, GFX_PIXEL_ON);

	//GFX_FillRectangle(&oled, 30, 15, 30, 10, GFX_PIXEL_ON);

	//GFX_DrawRectangle(&oled, 20, 10, 50, 20, GFX_PIXEL_ON);

	GFX_DrawLine(&oled, 5, 20, 60, 30, GFX_PIXEL_ON);

	SSD1306_Update(&oled);
	while(0)
	{

		for(uint16_t i=0;i<64;i++)
		{
			OLED_Status_t status = GFX_FillRectangle(&oled, 30, 5, i, i, GFX_PIXEL_ON);

			if(status != OLED_OKAY)
			{
				GFX_Clear(&oled);
				break;
			}
			SSD1306_Update(&oled);

			force_delay();
		}

	}
}












