/*
 * SPI_Baremetal.h
 *
 *  Created on: May 29, 2026
 *      Author: hp
 */

#ifndef INC_SPI_BAREMETAL_H_
#define INC_SPI_BAREMETAL_H_

/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "STM32F401RE.h"

void SPI_Configuration(void);
void SPI_Transmit_Byte(uint8_t byte);
uint8_t SPI_Receive_Byte();
void SPI_GPIO_Configurations();
void SPI_Loopback_Test();




















#endif /* INC_SPI_BAREMETAL_H_ */
